### ISSUE TITLE
Documentation is not sufficient.

### ISSUE THREAD

**Issue by krishna700** [alirezat775/carousel-view#4]
I want to use this library. But I don't find the documentation useful as there is less code on how to implement. Please update the readme with relevant code snippets. Thanks

**Comment by alirezat775** [comment]
I implemented a sample in the app module. your point is true, I will be added document

**Comment by alirezat775** [comment]
@krishna700 added a document for a library, you can find in [https://github.com/alirezat775/carousel-view/wiki](wiki)

**Comment by khaboshama91** [comment]
There isn't any documentation how to use the library. Please update the wiki.
