### ISSUE TITLE
Sliding images without resize animation

### ISSUE THREAD

**Issue by draskosaric** [alirezat775/carousel-view#5]
Hi!

First of all, this is really great and helpful library. I have a question, though.

I set carousel and when images are sliding, they change their sizes, like in picture below:

<img width="506" alt="Screen Shot 2019-09-10 at 11 39 06 AM" src="https://user-images.githubusercontent.com/2921485/64602953-eecae780-d3bf-11e9-891b-efd0486db67e.png">

**_Question:_** how can I set carousel to show images (or custom views) to just slide without resizing them? 

I tried to use `enableSlider(true)`, but I only get the same behavior, with images that are much bigger and they don't fit well in placeholder., something like this:

<img width="504" alt="Screen Shot 2019-09-10 at 11 48 24 AM" src="https://user-images.githubusercontent.com/2921485/64603734-21291480-d3c1-11e9-9fbb-a129b820d429.png">

The library version I am using is **1.0.0**, couldn't find **1.0.1**, you mentioned in [changelog](https://github.com/alirezat775/carousel-view/blob/development/CHANGELOG).

Thanks!

**Comment by alirezat775** [comment]
Hi @draskosaric, Sorry for delay answer to your issue,  when use enableSlider method, change automatically item size, so change the width of item to screen width & change the height of item to 70 * width.

**Comment by alirezat775** [comment]
You can calculate item size in own adapter and doesn't use ``` enableSlider ```. otherwise, you can set item height dynamically size
About version 1.1.0, I checked it and added it into release section

**Comment by draskosaric** [comment]
Thanks, I'll look into that!
