### ISSUE TITLE
Unable to use autoscroll feature

### ISSUE THREAD

**Issue by binaykumarrana** [alirezat775/carousel-view#7]
Auto-scroll is not working, any issue?

**Comment by alirezat775** [comment]
Could you please explain more? I didn't get what your problem, according to the sample app you can use auto-scroll

**Comment by binaykumarrana** [comment]
The auto-scroll feature doesn't start automatically, once the user touches on one of the items and scroll little then leave after that scroll starts automatically. Until the user touches and scrolls a bit it doesn't start.  Any issue or I am missing? I enabled auto-scroll programmatically or by XML both didn't work properly. Any more help would be appreciating. Thanks

**Comment by alirezat775** [comment]
I got what's your problem, let me debugging this issue, I will inform you as soon as possible. Thanks for reporting the issue.

**Comment by binaykumarrana** [comment]
Thanks

**Comment by binaykumarrana** [comment]
I will be waiting for your answer.

**Comment by alirezat775** [comment]
Hi @binaykumarrana, your issue fixed in version 1.1.1

**Comment by binaykumarrana** [comment]
Thanks
