### ISSUE TITLE
Round image view not showing

### ISSUE THREAD

**Issue by rommansabbir** [alirezat775/carousel-view#8]
Hi,
I tried to show a list of images (not local images, images fetching from a web link) like a carousel. For that, I had to redesign the UI you already provided in the example app. I used a card view with a specific corner radius, but the problem is occurring, it's not showing the round image properly. I deeply observed it, I notice that when images are not loaded properly (in this case image is fetching from a URL source) the card view is showing properly with the expected behavior I wanted, but when the image loading is done, it's just showing as regular image view.

Also, image view height & width not showing properly as I had defined or expected.

Android Studio: 3.6.
Emulator: Pixel 3A
Android Version: Android 10 

![image](https://user-images.githubusercontent.com/25950083/79067284-0c5a8980-7ce0-11ea-9a5e-ca92fc5a3447.png)
![image](https://user-images.githubusercontent.com/25950083/79067288-14b2c480-7ce0-11ea-868e-cb0f8b60a142.png)
![image](https://user-images.githubusercontent.com/25950083/79070217-21daae00-7cf6-11ea-8198-58eb3296d312.png)

**Comment by alirezat775** [comment]
I think this issue about your image-loader because your placeholder has a radius but the regular image does not have it.
